<?php

// -----------------------------------------
// semplice
// admin/atts/modules/gallery.php
// -----------------------------------------

$gallery = array(
	'uploads' => array(
		'title' => 'Images',
		'break' => '1,2,2',
		'data-hide-mobile' => true,
		'images' => array(
			'title'				=> 'Images',
			'hide-title'		=> true,
			'data-style-option' => true,
			'size'				=> 'span4',
			'data-input-type'	=> 'gallery-upload',
			'default'			=> '',
			'data-is-content' 	=> true,
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'style-class'		=> 'ce-dropzone ce-dropzone-no-unsplash gallery-upload',
		),
		'animation_status' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Animation',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'enabled',
			'switch-values' => array(
				'enabled'		=> 'On',
				'disabled'	 	=> 'Off',
			),
		),
		'animation' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Type',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'sgs-crossfade',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'sgs-crossfade,sgs-slide',
			'data-visibility-prefix'	=> 'ov-gal-animation',
			'switch-values' => array(
				'sgs-crossfade'	=> 'Fade',
				'sgs-slide'	 	=> 'Slide',
			),
		),
		'attraction' => array(
			'title'			=> 'Attraction',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 25,
			'min'			=> 0,
			'max'			=> 9999,
			'data-divider'  => 1000,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'save',
			'help'			=> 'Attracts the position of the slider to the selected slide. Higher attraction makes the slider move faster. Lower makes it move slower.',
		),
		'friction' => array(
			'title'			=> 'Friction',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 280,
			'min'			=> 0,
			'max'			=> 9999,
			'data-divider'  => 1000,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'save',
			'help'			=> 'Slows the movement of slider. Higher friction makes the slider feel stickier and less bouncy. Lower friction makes the slider feel looser and more wobbly.',
		),
	),
	'width-option' => array(
		'title' => 'Width',
		'break' => '1',
		'data-hide-mobile' => true,
		'hide-title' => true,
		'width' => array(
			'data-input-type' => 'onoff-switch',
			'title'		 	  => 'Scale Image to Grid',
			'size'		 	  => 'span4',
			'hide-title' => true,
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 	  => 'grid-width',
			'data-on'		  => 'grid-width',
			'data-off'		  => 'original',
			'help'		 => 'This will scale your images to the width of the grid. Turning it off will display your images at it\'s original size (unless they are bigger than the grid) and horizontally centered.',
		),
	),
	'cover-option' => array(
		'title' => 'Cover',
		'break' => '1',
		'data-hide-mobile' => true,
		'hide-title' => true,
		'cover_mode' => array(
			'data-input-type' => 'onoff-switch',
			'help' => 'If enabled your image gallery will be full width and full height like a cover.<br /><br />Only exception is that if your section has a custom height the gallery cover mode will use that height instead.<br /><br /><b>Important:</b><br/>To make this work please make sure that you only have 1 column in your section and that your section width is set to fluid with no gutters.',
			'hide-title' => true,
			'title'		 => 'Cover Mode',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'disabled',
			'data-on'		  => 'enabled',
			'data-off'		  => 'disabled',
		),
	),
	'autoplay-option' => array(
		'title' => 'Cover',
		'break' => '1,1',
		'data-hide-mobile' => true,
		'hide-title' => true,
		'autoplay' => array(
			'data-input-type' => 'onoff-switch',
			'title'		 => 'Autoplay',
			'hide-title' => true,
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'false',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'true,false',
			'data-visibility-prefix'	=> 'ov-gal-autoplay',
			'data-on'		  => 'true',
			'data-off'		  => 'false',
		),
		'timeout' => array(
			'data-input-type'	=> 'input-text',
			'title'		 	=> 'Timeout',
			'size'		 	=> 'span4',
			'placeholder'	=> '4000',
			'default'		=> '4000',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'style-class'	=> 'ov-gal-autoplay-true',
			'help'			=> 'This is the timeout between images in milliseconds. Minimum is 600ms.',
		),
	),
	'adaptive-height-option' => array(
		'title' => 'Cover',
		'break' => '1',
		'data-hide-mobile' => true,
		'hide-title' => true,
		'adaptive_height' => array(
			'data-input-type' => 'onoff-switch',
			'hide-title' => true,
			'help'			  => 'If \'enabled\' the height of the gallery slider always adapts to the height of the active slide.',
			'title'		 => 'Adaptive Height',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'true',
			'data-on'		  => 'true',
			'data-off'		  => 'false',
		),
	),
	'infinite-option' => array(
		'title' => 'Cover',
		'break' => '1',
		'data-hide-mobile' => true,
		'hide-title' => true,
		'infinite' => array(
			'data-input-type' => 'onoff-switch',
			'hide-title' => true,
			'help'			  => 'If enabled, your gallery will automatically restart after the last slide.',
			'title'		 => 'Infinite Slider',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'false',
			'data-on'		  => 'true',
			'data-off'		  => 'false',
		),
	),
	'arrows' => array(
		'title' => 'Arrows',
		'break' => '2',
		'data-hide-mobile' => true,
		'style-class' => 'ep-collapsed',
		'arrows_color' => array(
			'title'				=> 'Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> '#ffffff',
			'class'				=> 'color-picker',
		),
		'arrows_visibility' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Visibility',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'true',
			'switch-values' => array(
				'true'	 => 'Show',
				'false'  => 'Hide',
			),
		),
	),
	'pagination' => array(
		'title' => 'Pagination',
		'break' => '2,1',
		'data-hide-mobile' => true,
		'style-class' => 'ep-collapsed',
		'pagination_color' => array(
			'title'				=> 'Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> '#000000',
			'class'				=> 'color-picker',
		),
		'pagination_visibility' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Visibility',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'false',
			'switch-values' => array(
				'true'	 => 'Show',
				'false'  => 'Hide',
			),
		),
		'pagination_position' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Position',
			'size'		 => 'span4',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'below',
			'switch-values' => array(
				'below'	 => 'Below Image',
				'above'  => 'Above Image',
			),
		),
	),
);

?>